
<<<<<<< HEAD
spring.application.name=transcation
spring.datasource.url=jdbc:postgresql://localhost:5432/zaalima
=======
# =====================================================
# APPLICATION
# =====================================================
spring.application.name=VaultCore-Financial
server.port=8089
spring.datasource.url=jdbc:postgresql://localhost:5432/dashboard
>>>>>>> c9db6d00db9c98d9daee2928251090760a5a3095
spring.datasource.username=postgres
spring.datasource.password=Siy@123uikey
spring.datasource.driver-class-name=org.postgresql.Driver



<<<<<<< HEAD
# =====================================================
# JPA / HIBERNATE
# =====================================================
=======

>>>>>>> c9db6d00db9c98d9daee2928251090760a5a3095
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
<<<<<<< HEAD
server.port=8087

# =====================================================
# THYMELEAF (Frontend Templates)
# =====================================================
=======

>>>>>>> c9db6d00db9c98d9daee2928251090760a5a3095
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false


<<<<<<< HEAD
#
=======
# =====================================================
# JWT CONFIGURATION
# =====================================================
app.jwt.secret=ThisIsAVeryVeryLongAndSecureJwtSecretKey123456
app.jwt.expiration=86400000
app.jwt.refresh-exp-days=7

server.servlet.session.persistent=false
spring.session.store-type=none


#
>>>>>>> c9db6d00db9c98d9daee2928251090760a5a3095
