# ===============================
# Application
# ===============================
spring.application.name=admin_dashboard_user
server.port=8080

# ===============================
# PostgreSQL Database
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/zaalima
spring.datasource.username=postgres
spring.datasource.password=Siy@123uikey
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.security.enabled=false

# Thymeleaf
# ===============================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
