spring.application.name=transcation
spring.datasource.url=jdbc:postgresql://localhost:5432/VaultCore
spring.datasource.username=postgres
spring.datasource.password=Siy@123uikey
spring.datasource.driver-class-name=org.postgresql.Driver



# =====================================================
# JPA / HIBERNATE
# =====================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
server.port=8084

# =====================================================
# THYMELEAF (Frontend Templates)
# =====================================================
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false


# =====================================================
# JWT CONFIGURATION
# =====================================================
app.jwt.secret=ThisIsAVeryVeryLongAndSecureJwtSecretKey123456
app.jwt.expiration=86400000
app.jwt.refresh-exp-days=7

server.servlet.session.persistent=false
spring.session.store-type=none
